const { ROLES } = require('./roles');

const PERMISSIONS = Object.freeze({
  // Users
  USERS_VIEW: 'USERS_VIEW',
  USERS_VIEW_SELF: 'USERS_VIEW_SELF',
  USERS_CREATE: 'USERS_CREATE',
  USERS_UPDATE: 'USERS_UPDATE',
  USERS_UPDATE_SELF: 'USERS_UPDATE_SELF',
  USERS_DELETE: 'USERS_DELETE',
  USERS_LOCK: 'USERS_LOCK',
  USERS_UNLOCK: 'USERS_UNLOCK',
  USERS_TAGS_MANAGE: 'USERS_TAGS_MANAGE',
  USERS_FAMILY_LINK: 'USERS_FAMILY_LINK',
  USERS_UPLOAD_AVATAR: 'USERS_UPLOAD_AVATAR',
  USERS_UPLOAD_AVATAR_SELF: 'USERS_UPLOAD_AVATAR_SELF',

  // Auth
  AUTH_VIEW_SELF: 'AUTH_VIEW_SELF',
  AUTH_MANAGE_SESSIONS: 'AUTH_MANAGE_SESSIONS',
  AUTH_CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',

  // Confessions
  CONFESSIONS_VIEW: 'CONFESSIONS_VIEW',
  CONFESSIONS_CREATE: 'CONFESSIONS_CREATE',
  CONFESSIONS_ASSIGN_USER: 'CONFESSIONS_ASSIGN_USER',
  CONFESSIONS_SESSION_TYPES_MANAGE: 'CONFESSIONS_SESSION_TYPES_MANAGE',
  CONFESSIONS_ALERTS_VIEW: 'CONFESSIONS_ALERTS_VIEW',
  CONFESSIONS_ALERTS_MANAGE: 'CONFESSIONS_ALERTS_MANAGE',
  CONFESSIONS_ANALYTICS_VIEW: 'CONFESSIONS_ANALYTICS_VIEW',

  // Pastoral visitations
  PASTORAL_VISITATIONS_VIEW: 'PASTORAL_VISITATIONS_VIEW',
  PASTORAL_VISITATIONS_CREATE: 'PASTORAL_VISITATIONS_CREATE',
  PASTORAL_VISITATIONS_ANALYTICS_VIEW: 'PASTORAL_VISITATIONS_ANALYTICS_VIEW',

  // Sectors
  SECTORS_VIEW: 'SECTORS_VIEW',
  SECTORS_CREATE: 'SECTORS_CREATE',
  SECTORS_UPDATE: 'SECTORS_UPDATE',
  SECTORS_DELETE: 'SECTORS_DELETE',

  // Meetings
  MEETINGS_VIEW: 'MEETINGS_VIEW',
  MEETINGS_CREATE: 'MEETINGS_CREATE',
  MEETINGS_UPDATE: 'MEETINGS_UPDATE',
  MEETINGS_DELETE: 'MEETINGS_DELETE',
  MEETINGS_SERVANTS_MANAGE: 'MEETINGS_SERVANTS_MANAGE',
  MEETINGS_COMMITTEES_MANAGE: 'MEETINGS_COMMITTEES_MANAGE',
  MEETINGS_ACTIVITIES_MANAGE: 'MEETINGS_ACTIVITIES_MANAGE',
  MEETINGS_RESPONSIBILITIES_VIEW: 'MEETINGS_RESPONSIBILITIES_VIEW',
  MEETINGS_SERVANT_HISTORY_VIEW: 'MEETINGS_SERVANT_HISTORY_VIEW',
});

const PERMISSIONS_ARRAY = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: [...PERMISSIONS_ARRAY],
  [ROLES.ADMIN]: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_VIEW_SELF,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_UPDATE_SELF,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_LOCK,
    PERMISSIONS.USERS_UNLOCK,
    PERMISSIONS.USERS_TAGS_MANAGE,
    PERMISSIONS.USERS_FAMILY_LINK,
    PERMISSIONS.USERS_UPLOAD_AVATAR,
    PERMISSIONS.USERS_UPLOAD_AVATAR_SELF,
    PERMISSIONS.AUTH_VIEW_SELF,
    PERMISSIONS.AUTH_CHANGE_PASSWORD,
    PERMISSIONS.CONFESSIONS_VIEW,
    PERMISSIONS.CONFESSIONS_CREATE,
    PERMISSIONS.CONFESSIONS_ASSIGN_USER,
    PERMISSIONS.CONFESSIONS_SESSION_TYPES_MANAGE,
    PERMISSIONS.CONFESSIONS_ALERTS_VIEW,
    PERMISSIONS.CONFESSIONS_ALERTS_MANAGE,
    PERMISSIONS.CONFESSIONS_ANALYTICS_VIEW,
    PERMISSIONS.PASTORAL_VISITATIONS_VIEW,
    PERMISSIONS.PASTORAL_VISITATIONS_CREATE,
    PERMISSIONS.PASTORAL_VISITATIONS_ANALYTICS_VIEW,
    PERMISSIONS.SECTORS_VIEW,
    PERMISSIONS.SECTORS_CREATE,
    PERMISSIONS.SECTORS_UPDATE,
    PERMISSIONS.SECTORS_DELETE,
    PERMISSIONS.MEETINGS_VIEW,
    PERMISSIONS.MEETINGS_CREATE,
    PERMISSIONS.MEETINGS_UPDATE,
    PERMISSIONS.MEETINGS_DELETE,
    PERMISSIONS.MEETINGS_SERVANTS_MANAGE,
    PERMISSIONS.MEETINGS_COMMITTEES_MANAGE,
    PERMISSIONS.MEETINGS_ACTIVITIES_MANAGE,
    PERMISSIONS.MEETINGS_RESPONSIBILITIES_VIEW,
    PERMISSIONS.MEETINGS_SERVANT_HISTORY_VIEW,
  ],
  [ROLES.USER]: [
    PERMISSIONS.AUTH_VIEW_SELF,
    PERMISSIONS.AUTH_CHANGE_PASSWORD,
    PERMISSIONS.USERS_VIEW_SELF,
    PERMISSIONS.USERS_UPDATE_SELF,
    PERMISSIONS.USERS_UPLOAD_AVATAR_SELF,
  ],
});

module.exports = { PERMISSIONS, PERMISSIONS_ARRAY, ROLE_PERMISSIONS };
